### ISSUE TITLE
Provide both safe and unsafe alternatives for functions?

### ISSUE THREAD

**Issue by jsl** [stackbuilders/inflections-hs#19]
There are [some functions in the codebase that may throw an exception depending on the input](https://github.com/stackbuilders/inflections-hs/blob/master/Text/Inflections.hs#L137:L160). Should they be nested under and `Unsafe` module?

**Comment by mrkkrp** [comment]
I propose we use `MonadThrow` here. Depending on monad it will either throw an exception or return result inside of `Maybe`. You can see how it's used [here](https://hackage.haskell.org/package/path-0.5.8/docs/Path.html#v:parseAbsDir) for example.

**Comment by mrkkrp** [comment]
And in the excptions we could actually include complete parsing error.

**Comment by mrkkrp** [comment]
Resolved as part of #38, now we don't have partial functions in the library at all.
