### ISSUE TITLE
Update Travis CI script

### ISSUE THREAD

**Issue by mrkkrp** [stackbuilders/inflections-hs#29]
Several propositions:

* The build should fail if Haddock coverage is not 100%.

* Use Cabal. The reason to use Cabal on Travis is that allows to test the package is more “adverse” environment. In other words, it's desirable that open source packages build with Cabal too. If a package builds with Cabal, it will sure build with Stack as well. We also can add GHC 8 to the build matrix without waiting for lts that supports it.

I personally use Cabal on Travis for open source and Stack for my personal projects that others won't use, so I recommend this.

**Comment by CristhianMotoche** [comment]
I though this library was supporting 7.8 and 7.10 GHC versions, according to #23.
I think it will always fails with GHC 7.6, because of `hspec-discover`.

**Comment by mrkkrp** [comment]
Yeah, I can see the logs. Patience, I'll make it work by the end of the day for all GHCs.

**Comment by CristhianMotoche** [comment]
That will be awesome. Thanks!
