### ISSUE TITLE
add pluralize & singularize

### ISSUE THREAD

**Issue by tippenein** [stackbuilders/inflections-hs#37]
~Feature Request~
I need something like this:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb

It would seem appropriate to put this functionality along with your work.

**Comment by tippenein** [comment]
Initial tested "irregular" countables [here](https://github.com/tippenein/inflections-hs/commit/8ae4c67bd7e8c3faf93b782da1e3144e21c3a068#diff-4e721c548aa3b69bd0de30a3669d8260R9)

I'm not sure the best way to generate [this](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb) mapping is though. You might not want to add a regex dependency and generating the singular/plural versions of these into a Bimap is not plausible.

**Comment by tippenein** [comment]
#41 implements this

**Comment by elcuy** [comment]
Closing this since it's solved
