### ISSUE TITLE
Add purpose of this library

### ISSUE THREAD

**Issue by chshersh** [stackbuilders/inflections-hs#54]
It's not clear from `README.md` why I may want to use this library. Though, it looks cool, it's actively maintained, even uses `megaparsec` instead of `parsec`! But I think that it would be good to have 2-3 examples of problems which can be solved with this library.

**Comment by elcuy** [comment]
Hi, thank you for your feedback! It's a great idea, I will get into it as soon as possible.

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add purpose of this library](https://trello.com/c/gwzBLqPf/41-add-purpose-of-this-library)

**Comment by Centeno448** [comment]
Solved by #58
