### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/inflections-hs#9]
Add to [Stackage](https://www.stackage.org/).

**Comment by jpvillaisaza** [comment]
@jsl Can I add this package to Stackage? I tried it with LTS Haskell and Stackage Nightly. It works.

**Comment by jsl** [comment]
@jpvillaisaza sure, go for it. Thanks!

**Comment by jpvillaisaza** [comment]
Done.

See https://github.com/fpco/stackage/commit/62770fbdf31bfd9b3b1d98b7d6fe527e5853db10.
